server:
  port: 8888

spring:
  application:
    name: zmj-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/T3World/config-server
          timeout: 5
          searchPaths: zmj
          force-pull: true
          username: T3World
          password: umr1316190
#配置actuator健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
