server:
  port: 7900
spring:
  application:
    name: provider-user
#  main:
#    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  level:
    root: INFO