server:
  port: 8080
spring:
  application:
    name: zmj-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      enabled: true
      routes:
      - id: user_route
        uri: http://127.0.0.1:7900/hello
        predicates:
        - Path=/test
#        filters:
#        - PrefixPath=/hello
#        - SetPath=/hello
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
